# Generated by Django 5.2.8 on 2025-11-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
