# Generated by Django 5.2.8 on 2025-11-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_task_title_task_title_encrypted_userkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title_encrypted',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserKey',
        ),
    ]
