# Generated by Django 5.2.8 on 2025-11-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_task_title_encrypted_task_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
