# Generated by Django 5.2.8 on 2025-11-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='UserKey',
        ),
    ]
